//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LinkbacksModel", "FK_Comment_Post", "Post", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcDemo.Models.Post), "Comment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcDemo.Models.Comment))]

// Original file name:
// Generation date: 06.03.2009 21:40:41
namespace MvcDemo.Models
{
    
    /// <summary>
    /// There are no comments for LinkbacksEntities in the schema.
    /// </summary>
    public partial class LinkbacksEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LinkbacksEntities object using the connection string found in the 'LinkbacksEntities' section of the application configuration file.
        /// </summary>
        public LinkbacksEntities() : 
                base("name=LinkbacksEntities", "LinkbacksEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LinkbacksEntities object.
        /// </summary>
        public LinkbacksEntities(string connectionString) : 
                base(connectionString, "LinkbacksEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LinkbacksEntities object.
        /// </summary>
        public LinkbacksEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LinkbacksEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Comment> Comment
        {
            get
            {
                if ((this._Comment == null))
                {
                    this._Comment = base.CreateQuery<Comment>("[Comment]");
                }
                return this._Comment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Comment> _Comment;
        /// <summary>
        /// There are no comments for Post in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Post> Post
        {
            get
            {
                if ((this._Post == null))
                {
                    this._Post = base.CreateQuery<Post>("[Post]");
                }
                return this._Post;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Post> _Post;
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
        /// <summary>
        /// There are no comments for Post in the schema.
        /// </summary>
        public void AddToPost(Post post)
        {
            base.AddObject("Post", post);
        }
    }
    /// <summary>
    /// There are no comments for LinkbacksModel.Comment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LinkbacksModel", Name="Comment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Comment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="content">Initial value of Content.</param>
        /// <param name="from">Initial value of From.</param>
        public static Comment CreateComment(int id, global::System.DateTime created, string content, string from)
        {
            Comment comment = new Comment();
            comment.Id = id;
            comment.Created = created;
            comment.Content = content;
            comment.From = from;
            return comment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property From in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string From
        {
            get
            {
                return this._From;
            }
            set
            {
                this.OnFromChanging(value);
                this.ReportPropertyChanging("From");
                this._From = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("From");
                this.OnFromChanged();
            }
        }
        private string _From;
        partial void OnFromChanging(string value);
        partial void OnFromChanged();
        /// <summary>
        /// There are no comments for Post in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LinkbacksModel", "FK_Comment_Post", "Post")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Post Post
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Post>("LinkbacksModel.FK_Comment_Post", "Post").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Post>("LinkbacksModel.FK_Comment_Post", "Post").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Post in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Post> PostReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Post>("LinkbacksModel.FK_Comment_Post", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Post>("LinkbacksModel.FK_Comment_Post", "Post", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LinkbacksModel.Post in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LinkbacksModel", Name="Post")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Post : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="content">Initial value of Content.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Post CreatePost(int id, global::System.DateTime created, string content, string title)
        {
            Post post = new Post();
            post.Id = id;
            post.Created = created;
            post.Content = content;
            post.Title = title;
            return post;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LinkbacksModel", "FK_Comment_Post", "Comment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Comment> Comments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Comment>("LinkbacksModel.FK_Comment_Post", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Comment>("LinkbacksModel.FK_Comment_Post", "Comment", value);
                }
            }
        }
    }
}
